// Mock Data for Testing

export const mockCategories = [
    { id: 1, name: 'Burgers', slug: 'burgers' },
    { id: 2, name: 'Pizza', slug: 'pizza' },
    { id: 3, name: 'Fried Chicken', slug: 'fried-chicken' },
    { id: 4, name: 'Wraps', slug: 'wraps' },
    { id: 5, name: 'Desserts', slug: 'desserts' },
    { id: 6, name: 'Pasta', slug: 'pasta' },
];

export const mockMenuItems = [
    {
        id: 1,
        name: 'Classic Smash Burger',
        slug: 'classic-smash-burger',
        description: 'Double smashed patty, cheddar, caramelized onions, pickles & special sauce',
        price: 14.99,
        category: mockCategories[0],
        category_id: 1,
        is_available: true,
        image_url: null,
        rating: 4.8,
        reviews: 50,
    },
    {
        id: 2,
        name: 'Margherita Royale',
        slug: 'margherita-royale',
        description: 'San Marzano tomatoes, buffalo mozzarella, basil & truffle oil',
        price: 19.99,
        category: mockCategories[1],
        category_id: 2,
        is_available: true,
        image_url: null,
        rating: 4.7,
        reviews: 45,
    },
    {
        id: 3,
        name: 'Nashville Hot Chicken',
        slug: 'nashville-hot-chicken',
        description: 'Crispy fried chicken in fiery Nashville spice blend with honey',
        price: 12.99,
        category: mockCategories[2],
        category_id: 3,
        is_available: true,
        image_url: null,
        rating: 4.9,
        reviews: 78,
    },
    {
        id: 4,
        name: 'Mediterranean Wrap',
        slug: 'mediterranean-wrap',
        description: 'Grilled chicken, hummus, feta, cucumber, tomato & tzatziki',
        price: 11.99,
        category: mockCategories[3],
        category_id: 4,
        is_available: true,
        image_url: null,
        rating: 4.6,
        reviews: 32,
    },
    {
        id: 5,
        name: 'Chocolate Lava Cake',
        slug: 'chocolate-lava-cake',
        description: 'Warm chocolate cake with molten center, served with vanilla ice cream',
        price: 8.99,
        category: mockCategories[4],
        category_id: 5,
        is_available: true,
        image_url: null,
        rating: 4.9,
        reviews: 120,
    },
    {
        id: 6,
        name: 'Carbonara Pasta',
        slug: 'carbonara-pasta',
        description: 'Creamy carbonara with pancetta, pecorino romano & fresh cracked pepper',
        price: 15.99,
        category: mockCategories[5],
        category_id: 6,
        is_available: true,
        image_url: null,
        rating: 4.8,
        reviews: 67,
    },
    {
        id: 7,
        name: 'Spicy Chicken Burger',
        slug: 'spicy-chicken-burger',
        description: 'Crispy chicken breast, jalapeños, pepper jack cheese & sriracha mayo',
        price: 13.99,
        category: mockCategories[0],
        category_id: 1,
        is_available: true,
        image_url: null,
        rating: 4.7,
        reviews: 55,
    },
    {
        id: 8,
        name: 'Pepperoni Supreme',
        slug: 'pepperoni-supreme',
        description: 'Loaded with pepperoni, sausage, mushrooms & mozzarella',
        price: 18.99,
        category: mockCategories[1],
        category_id: 2,
        is_available: true,
        image_url: null,
        rating: 4.8,
        reviews: 89,
    },
];

export const mockOrders = [
    {
        id: 1,
        order_number: 'ORD-20240525-001',
        user_id: 1,
        type: 'dine-in',
        status: 'completed',
        table_number: '5',
        subtotal: 45.97,
        total: 50.57,
        notes: 'No onions please',
        created_at: '2024-05-25T10:30:00',
        items: [
            {
                id: 1,
                menu_item_name: 'Classic Smash Burger',
                menu_item_price: 14.99,
                quantity: 2,
                customization_notes: 'Extra cheese',
            },
            {
                id: 2,
                menu_item_name: 'Margherita Royale',
                menu_item_price: 19.99,
                quantity: 1,
                customization_notes: null,
            },
        ],
    },
    {
        id: 2,
        order_number: 'ORD-20240525-002',
        user_id: 1,
        type: 'delivery',
        status: 'ready',
        delivery_address: '123 Main St, Apt 4B, New York, NY 10001',
        subtotal: 32.98,
        total: 36.28,
        notes: 'Ring doorbell twice',
        created_at: '2024-05-25T14:15:00',
        items: [
            {
                id: 3,
                menu_item_name: 'Nashville Hot Chicken',
                menu_item_price: 12.99,
                quantity: 2,
                customization_notes: 'Extra spicy',
            },
            {
                id: 4,
                menu_item_name: 'Mediterranean Wrap',
                menu_item_price: 11.99,
                quantity: 1,
                customization_notes: null,
            },
        ],
    },
    {
        id: 3,
        order_number: 'ORD-20240525-003',
        user_id: 1,
        type: 'takeaway',
        status: 'preparing',
        subtotal: 24.98,
        total: 27.48,
        notes: null,
        created_at: '2024-05-25T16:45:00',
        items: [
            {
                id: 5,
                menu_item_name: 'Chocolate Lava Cake',
                menu_item_price: 8.99,
                quantity: 2,
                customization_notes: 'Extra ice cream',
            },
            {
                id: 6,
                menu_item_name: 'Carbonara Pasta',
                menu_item_price: 15.99,
                quantity: 1,
                customization_notes: null,
            },
        ],
    },
    {
        id: 4,
        order_number: 'ORD-20240524-001',
        user_id: 1,
        type: 'dine-in',
        status: 'completed',
        table_number: '8',
        subtotal: 38.97,
        total: 42.87,
        notes: null,
        created_at: '2024-05-24T19:00:00',
        items: [
            {
                id: 7,
                menu_item_name: 'Spicy Chicken Burger',
                menu_item_price: 13.99,
                quantity: 2,
                customization_notes: null,
            },
            {
                id: 8,
                menu_item_name: 'Pepperoni Supreme',
                menu_item_price: 18.99,
                quantity: 1,
                customization_notes: 'Light sauce',
            },
        ],
    },
];

export const mockReservations = [
    {
        id: 1,
        reservation_number: 'RES-20240525-001',
        user_id: 1,
        reserved_date: '2024-05-26',
        reserved_time: '19:00',
        party_size: 4,
        status: 'confirmed',
        special_requests: 'Window seat if available',
        created_at: '2024-05-25T10:00:00',
    },
    {
        id: 2,
        reservation_number: 'RES-20240525-002',
        user_id: 1,
        reserved_date: '2024-05-27',
        reserved_time: '20:30',
        party_size: 2,
        status: 'pending',
        special_requests: 'Celebration dinner - anniversary',
        created_at: '2024-05-25T11:30:00',
    },
    {
        id: 3,
        reservation_number: 'RES-20240524-001',
        user_id: 1,
        reserved_date: '2024-05-24',
        reserved_time: '18:00',
        party_size: 6,
        status: 'completed',
        special_requests: null,
        created_at: '2024-05-24T09:00:00',
    },
];

export const mockUser = {
    id: 1,
    name: 'John Doe',
    email: 'john@example.com',
    phone: '+1 (555) 123-4567',
    roles: ['customer'],
};

export const mockDashboardStats = {
    todayOrders: 12,
    todayRevenue: 487.50,
    pendingOrders: 3,
    todayReservations: 8,
    pendingReservations: 2,
    activeMenuItems: 24,
    categories: 6,
    recentOrders: mockOrders.slice(0, 5),
    todayReservationsList: mockReservations.slice(0, 5),
};

export const mockRestaurantInfo = {
    name: 'Sarah',
    tagline: 'Experience culinary excellence',
    address: '42 Flower Street, New York, NY 10001',
    hours: {
        monday: '11:00 AM - 10:00 PM',
        tuesday: '11:00 AM - 10:00 PM',
        wednesday: '11:00 AM - 10:00 PM',
        thursday: '11:00 AM - 10:00 PM',
        friday: '11:00 AM - 11:00 PM',
        saturday: '10:00 AM - 11:00 PM',
        sunday: '10:00 AM - 9:00 PM',
    },
    phone: '+1 (800) 123-4567',
    email: 'hello@sarahfood.com',
};
